# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1
language: objective-c

branches:
 only:
 - master

install:
    - gem install cocoapods -v 1.0.1 --no-document

before_script:
    - cd Example
    - pod install

script: 
    - xcodebuild build test -workspace NumberMorphView.xcworkspace -scheme NumberMorphView-Example -destination "platform=iOS Simulator,name=iPhone X,OS=11.1"
